### ISSUE TITLE
Suggestion: CVAR to enable/disable player collisions?

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#103]
Title.
Something so that we don't have to use external plugins like No Block
https://forums.alliedmods.net/showthread.php?p=462813

**Comment by arenaceous** [comment]
If this is implemented, there should be 4 modes.
Everyone is solid
Your team is non-solid
The other team is non-solid
No teams are solid.

**Comment by TheZoc** [comment]
There is a plugin for this. Why avoid using the plugin?
It surely will be more updated that the mod code, if something breaks

**Comment by Melectrome** [comment]
The plugin only has one option, namely:
Everyone is non-solid.

This is why I wanted to see this become a cvar, server owners not interested in sourcemod could have this functionality enabled easily, and they'd have more options like arena suggested

**Comment by TheZoc** [comment]
This seems to be a lot of work to add tbh.
I'm hesitant to add it due to the experience with the "last frozer" plugin, that led to a bunch of crashes and took a while to find out wtf was wrong :(

That team based collision could be trouble and require major modifications... (I don't recall how Source handles all of it).

I'd recommend changing that plugin to check the phase the game is in and only add that on build phase.

(I don't understand how that plugin changes the collision data, and no mention of COLLISION_GROUP_PLAYER or its value)

**Comment by TheZoc** [comment]
I'll be closing this, but as always, feel free to reopen it if needed :)
