### ISSUE TITLE
Fort Saving

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#111]
Some way of saving/loading a fort (ideally in plain text) would be awesome. Ideally it should bug you if you load a fort on the wrong map, but you should be able to override it.
Everyone should be able to save a fort, but only server admins can load a fort
You should be able to set fort name as well. Ideally saved to a forts folder in sfclassic.

Options:
Save all
Save only red
Save only blue
Save all as red
Save all as blue

Load all
Load only red
Load only blue
(Ideally there would be more advance dialog with loading to set offsets, and rotations around the flag/swapping teams etc. A preview would be awesome for this).

**Comment by Melectrome** [comment]
This can be done with server plugins and shouldn't be a built-in feature, as coding it may take a long time

**Comment by TheZoc** [comment]
This was planned and partially implemented in Haven/SourceSDK, but it wasn't complete, so it's hard to port over.
This is planned for SourceForts 2/UE4, not yet implemented.

SourceForts Classic doens't have the basic structure to allow it and changing it could require major code changes, even if partially implemented in a different way.

Sadly, this isn't trivial as it sounds to be polished and working without issues and will take a long time.
Believe me, I really wanted that feature in for years now... Sadly, won't happen.

Also, since @Melectrome said that can be done with a server plugin, that could be an awesome route to follow. There's a simple method to check if an entity is a block (from previous partial implementation): Any entity that returns true to `IsBlock()` is a block. All the blocks are `CPhysicsPropBlock` entities.
(Yeah, the current codebase isn't the best one, that's why sometimes I'm hesitant to make major changes - but hey, you have two ways to detect that if you're strong about creating this plugin! 😁 )

**Comment by TheZoc** [comment]
I"m closing this, so it won't keep bugging me, but if you want to create a plugin for this, need a place to debase or need this open to remind someone else about working on it, feel free to reopen it 😄
