### ISSUE TITLE
2nd ammo for smg doesn't work

### ISSUE THREAD

**Issue by Nick12506** [TheZoc/sourceforts-bug-tracker#19]
^

**Comment by TheZoc** [comment]
Which one is supposed to be this one? Team smoke grenade?

**Comment by Nick12506** [comment]
It's should be a grenade launcher by default though team smoke grenades are a way better plan imo

**Comment by Melectrome** [comment]
2nd ammo for soldiers gun (idk what was the name of it) also doesnt work

**Comment by Nick12506** [comment]
^ ar2

**Comment by TheZoc** [comment]
SMG1: Secondary fire is disabled. I think it was disable right before releasing the game, due to the removal of the smoke grenade.
More info here: https://www.youtube.com/watch?v=PYS8q85SOfY


AR2: The code for `CreateCombineBall()` was removed in SF194 (I think it wasn't there since SF192, but I don't have the source code to check)


Do any of these need to be changed?

Please, in the future, create one topic for each weapon :)

**Comment by Nick12506** [comment]
Readd SMG1 smoke grenades?

**Comment by TheZoc** [comment]
- Added the cut feature Smoke Grenades from Sourceforts 1.9.4.1 to Scout's SMG1
  - Fixed Scout's SMG1 secondary fire.
  - Added `sf_scout_smoke_grenade` server variable to configure the amount of smoke grenade the scout class spawns. Defaults to 0.
  - By default, players spawn with no grenades. This is a feature easy to abuse and it was added mostly for fun.
  - The smoke grenade behaves differently from Sourceforts 1.9.4.1 mostly due to changes in Source SDK itself. This might never be fixed.
  - It's easy to abuse this feature (with suicides/respawns). Don't turn it on, on public servers.
  - I'm still considering adding a limit timer to it, but might be more trouble than it's worth.
- Added ar2 alt fire (combine ball) back in
  - This should be considered a Fun feature! It shouldn't ever be enabled on public servers or competitive play!
  - Added `sf_soldier_combineball_enabled` console variable to control if the player can actually shoot combine balls. Default: 0
  - Added `sf_soldier_combineball` console variable to control the amount of ammo the player will spawn. (Will not work if `sf_soldier_combineball_enabled` is set to 0!). Default: 0
  - This "double lock" variable system might be silly, but it's easier to prevent an exploit that way.
