### ISSUE TITLE
Crete Checker Texture

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#25]
The crete checker texture does not tile correctly. I have updated the textures 8 years ago, but have attached them here. VTF textures need to be placed in materials/sf/sf_crete

[sf_crete.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2613633/sf_crete.zip)

**Comment by ghost** [comment]
- before:
![screenshot-2018-11-27-05_41_11](https://user-images.githubusercontent.com/45349537/49059019-16710a80-f207-11e8-8bd6-b2ebb8b7ed36.png)

- after:
![screenshot-2018-11-27-05_39_50](https://user-images.githubusercontent.com/45349537/49059030-212b9f80-f207-11e8-9af2-c1a50a0eac8e.png)

**Comment by arenaceous** [comment]
I shuffled the blocks on purpose. The other issue was the seam at the bottom (the trim by the floor). You can see in your screenshots by the doorway. (Albeit a bit small)

**Comment by TheZoc** [comment]
Added to Beta 11!

**Comment by Nick12506** [comment]
Would this change effect maps using this texture? If so then you might as well pak this into the map so that other maps are not effected by the change in positioning on the texture.

Include it as a new file in SF so that new maps can use the correct version and using the pak on the old version so that the old ones still fixed.
