### ISSUE TITLE
Sprays do not work

### ISSUE THREAD

**Issue by j2k3k** [TheZoc/sourceforts-bug-tracker#32]
The sound activates but no spray is applied when the button is pressed.

**Comment by arenaceous** [comment]
Related to this and to indirectly #26, the sprays included in SF are missing their .vmt files.
in materials/vgui/ delete the current logos folder, and replace with the one attached.
[logos.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2618367/logos.zip)

**Comment by TheZoc** [comment]
@arenaceous, There are tons of sprays without corresponding files on `logos/ui`. What's up with these?

**Comment by arenaceous** [comment]
These point to the textures either in the multiplayer 2013 files or the textures in the folder below. The sprays were a bit weird, this is what worked.

**Comment by TheZoc** [comment]
Okay, I added the files... I'm closing this, for now :)

**Comment by Melectrome** [comment]
this needs to be reopened

**Comment by TheZoc** [comment]
As explained by @L1pE, this is a bug on Source SDK 2013.
You need to set it on options (or through `cl_logofile` convar) before joining a game to work.
You can add this to `autoexec.cfg`, so it is set everytime the game starts, as a workaround.

Also, this bug isn't fixable, since we don't have access to the area of the code that declares cl_logofile
