### ISSUE TITLE
SLAM attachment

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#45]
Currently you can partially attach SLAMs to players, using the time when deploying while looking at the ground to quickly look up. These are not fixed to the players and will float. Similarly, you can actually put a SLAM on a deployed flag, and it will place happily, but not be fixed to the flag. In this case when the flag is picked up the SLAM will again float. In both cases, SLAMs I think should properly attach to the object it is placed on, and explode when said object is moved.

**Comment by Melectrome** [comment]
Out of curiosity, is this present in 1.9.4.1 too?

**Comment by arenaceous** [comment]
Yes, but I would consider this buggy behaviour.

**Comment by TheZoc** [comment]
There are some fixes on Tony Sergi fork that can change that behavior, but it might change it a lot. I can add them if you think it's worth it.

**Comment by arenaceous** [comment]
I think those changes might be worth it for the SLAMs

**Comment by arenaceous** [comment]
You can still mine a flag with SLAMs and then pick it up and the SLAMs will hover. Same goes for a block, you can unfreeze a block and the SLAMs attached to the block will still float.

**Comment by TheZoc** [comment]
There are 3 slam fixes on TonySergi fork:

- https://github.com/tonysergi/source-sdk-2013/commit/383c9235725a901bb719c4e5fd8d479c8db10198 - This was already fixed in SF using a different way.. I changed to this one for code clarity.
- https://github.com/tonysergi/source-sdk-2013/commit/c6576b431aac823dba68d0429d323da5d54b3e68 - This changes how it attaches. I haven't checked the code specifics yet (I'd appreciate an extra pair of eyes helping here)
- https://github.com/tonysergi/source-sdk-2013/commit/11b50445a8c2d4a604288aad4e94c82f8454f3f9 - Allows slams to be shot by enemies. Do we want that?

Tell me what's appropriate and I'll gladly add it :)

**Comment by arenaceous** [comment]
All of them?

**Comment by TheZoc** [comment]
Blindly applying it could be a problem (specially the 2nd one on that list). Could change a lot of their behavior.

Also, the 3rd fix could be a strong counter to it to the point it gets to be useless. Do we want that?

(Please, someone try taking a look at the code!)

**Comment by TheZoc** [comment]
Added those patches to Beta 14 :)
