### ISSUE TITLE
Game Rename

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#50]
After a little discussion in Discord with Jake and Draken and Acer, we think it might be a good idea if we rename this upcoming beta/release to SourceForts Classic. Additionally the mod folder should change to sfclassic. This would allow side by side testing of the two versions for bug testing, and would also mean that an install of SourceForts Classic would not write over 1.9.4.1 releases. This would also prep for the release of SourceForts 2 which could just be called SourceForts.

**Comment by Nick12506** [comment]
He mentioned it might be impossible, if so just rename that old folder so that old installations are not deleted like last time.

**Comment by arenaceous** [comment]
I dont get why this is impossible as I can safely rename the folder and run SF with out problems.

**Comment by Melectrome** [comment]
@arenaceous But when you try to join a normal server, you can't play simply because the server has a different mod folder (for example you may have the folder named to /sourceforts196/ but the server has /sourceforts/)

EDIT: Yeah now that I think of it it's a simple change, just change the folder name in the client installer in the final product and ask server operators to use the same name for their mod folder :p

**Comment by TheZoc** [comment]
once upon a time (SF193-194 betas), we had real issues with renaming them.. I remember e wanted a beta folder to be able to test it side by side with the regular installation... Yet, it causes a few untraceable bugs to appear, which disappeared when we renamed back.

I don't recall what bugs appeared.

I plan to rename this for release candidate or something like that :)

**Comment by TheZoc** [comment]
Changed folder to `sfclassic/`
Changed name to `SourceForts Classic 1.0`

Did I miss anything? :)
